name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 15 7 * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Гэтая задача пратэрмінавана праз неактыўнасць'
        stale-pr-message: 'Гэты запыт на змены патэрмінаваны праз неактыўнасць'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
