name: Publish Website
on:
  push
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Pull code from GitHub
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: Upload files by FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "public"
          remoteDir: "/www/mienskbiketour.by"
          # see docs: https://github.com/sebastianpopp/ftp-action
