name: Publish Website

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy by FTP'
    runs-on: ubuntu-latest
    steps:
      - name: Pull code from GitHub
        uses: actions/checkout@v3

      - name: Upload files by FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
            host: ${{ secrets.FTP_SERVER }}
            user: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            localDir: "public"
            remoteDir: "/www/mienskbiketour.by"
            # see docs: https://github.com/sebastianpopp/ftp-action
            # secrets:: https://github.com/miensk-bike-tour/mienskbiketour.by/settings/secrets/actions
