name: Publish Website

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: 'Deploy by FTP'
    runs-on: ubuntu-latest
    concurrency: deploy-mienskbiketour
    steps:
      - name: Pull code from GitHub
        uses: actions/checkout@v3

      - name: Upload files by FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: "public"
            server-dir: "/www/mienskbiketour.by"
