name: Publish Website

on:
  workflow_dispatch:
  push:
    paths:
      - '**.html'
      - '**.js'
      - '**.css'
      - '**.jpg'
      - '**.png'
      - '**.svg'

jobs:
  deploy:
    name: 'Deploy by FTP'
    runs-on: ubuntu-latest
    concurrency: deploy-mienskbiketour
    steps:
      - name: Pull code from GitHub
        uses: actions/checkout@v3

      - name: Upload files by FTP
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        with:
            FTP_SERVER: ${{ secrets.FTP_SERVER }}
            FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
            FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
            LOCAL_DIR: "public"
            REMOTE_DIR: "/www/mienskbiketour.by"
